### ISSUE TITLE
error when launching discord

### ISSUE THREAD

**Issue by plopomi** [giorgi-o/CrossPlatformPlaying#1]
hey, I'm getting an error everytime i launch discord :
 "
Error happened!
Your CrossPlatformPlaying config JSON is invalid!
Try putting it into an online JSON formatter to look for any errors.
TypeError: Cannot read property 'hasShownChangelog' of undefined"

**Comment by giorgi-o** [comment]
That most likely means your config file got corrupted somehow.
Go to BetterDiscord's plugin folder and locate the file called `CrossPlatformPlaying.json`.
From there, you can either:
- Go the easy way and just delete it (losing your config data in the process)
- Or you can open it with Nodepad and paste the contents into a [JSON formatter](https://jsonformatter.curiousconcept.com/) to try to find and fix the error.

**Comment by giorgi-o** [comment]
Nevermind, it's actually a bug lol. Pushing the update now.

**Comment by giorgi-o** [comment]
Resolved in https://github.com/giorgi-o/CrossPlatformPlaying/commit/1052dae6e1007c020f6f762cab35989214bcdb92.
