### ISSUE TITLE
How do I get a Twitch OAuth Key?

### ISSUE THREAD

**Issue by serg06** [giorgi-o/CrossPlatformPlaying#4]
Hello, I noticed this in your code:

https://github.com/giorgi-o/CrossPlatformPlaying/blob/2dfb2ec533773adb0be0aaf184157ff8f054c63b/CrossPlatformPlaying.plugin.js#L1676

I tried getting one with [TwitchTokenGenerator](https://twitchtokengenerator.com/), but even with all permissions enabled, it didn't work.

Could you please explain how to get the right key?

**Comment by giorgi-o** [comment]
Yeah, it's about time I wrote a guide on how to get the key, lol.
This guide should work on most browsers.

1. Go to [twitch.tv](https://twitch.tv), and make sure you're logged in
2. Press `F12` (or `Ctrl+Shift+I`/`⌥⌘I`) to open the devtools, and head to the `Network` tab on the top right
3. Wait for a request called `gql` to appear, try navigating to different streams until it does
4. Click on it, and on the panel that opens, scroll down to the `Request Headers` section and find the `Authorization` header

![image](https://user-images.githubusercontent.com/20621396/158690026-a414c076-59e1-450c-9ebe-f2f20c20e1f8.png)

Some GQL queries don't include the header, so just keep trying until you find one that does.

Once you do, your twitch key is the part **after** `OAuth`. Enjoy!

**Comment by serg06** [comment]
Thank you @giorgi-o . I guess there's no automated way of doing it, that's too bad.
