### ISSUE TITLE
Invalid Access Token, thinks my token is play-valorant-web-prod

### ISSUE THREAD

**Issue by ZeddPerm** [giorgi-o/CrossPlatformPlaying#5]
![image](https://user-images.githubusercontent.com/73501536/179326938-6e1d5f9e-4974-438d-8ba2-aa046e9e688e.png)

**Comment by giorgi-o** [comment]
Yeah, that's what happens when Riot doesn't like your cookies. Double check they're correct :)

**Comment by Ashesh3** [comment]
> ![image](https://user-images.githubusercontent.com/73501536/179326938-6e1d5f9e-4974-438d-8ba2-aa046e9e688e.png)

This helped me,

1. Open a new tab
2. Open developer tools
3. Go to networks tab
4. Make sure "Preserve log" is selected
5. Now visit `https://auth.riotgames.com/authorize?redirect_uri=https%3A%2F%2Fplayvalorant.com%2Fopt_in&client_id=play-valorant-web-prod&response_type=token%20id_token&scope=account%20ban%20link%20lol%20offline_access%20openid&nonce=123` this link on the same tab
6. See the cookies in Request headers for that specific page 
7. Paste the cookies in the plugin's settings

![image](https://user-images.githubusercontent.com/3626859/179371572-14441caa-6124-4dd1-9d3f-ed77e43d5b9e.png)

**Comment by ZeddPerm** [comment]
> > ![image](https://user-images.githubusercontent.com/73501536/179326938-6e1d5f9e-4974-438d-8ba2-aa046e9e688e.png)
> 
> This helped me,
> 
> 1. Open a new tab
> 2. Open developer tools
> 3. Go to networks tab
> 4. Make sure "Preserve log" is selected
> 5. Now visit `https://auth.riotgames.com/authorize?redirect_uri=https%3A%2F%2Fplayvalorant.com%2Fopt_in&client_id=play-valorant-web-prod&response_type=token%20id_token&scope=account%20ban%20link%20lol%20offline_access%20openid&nonce=123` this link on the same tab
> 6. See the cookies in Request headers for that specific page
> 7. Paste the cookies in the plugin's settings
> 
> ![image](https://user-images.githubusercontent.com/3626859/179371572-14441caa-6124-4dd1-9d3f-ed77e43d5b9e.png)

Thank you, this fixed the issue for me. However, my cookies had a lot more parameters than yours, so I only copied the sub, csid, and ssid.

**Comment by Ashesh3** [comment]
> > > ![image](https://user-images.githubusercontent.com/73501536/179326938-6e1d5f9e-4974-438d-8ba2-aa046e9e688e.png)
> > 
> > 
> > This helped me,
> > 
> > 1. Open a new tab
> > 2. Open developer tools
> > 3. Go to networks tab
> > 4. Make sure "Preserve log" is selected
> > 5. Now visit `https://auth.riotgames.com/authorize?redirect_uri=https%3A%2F%2Fplayvalorant.com%2Fopt_in&client_id=play-valorant-web-prod&response_type=token%20id_token&scope=account%20ban%20link%20lol%20offline_access%20openid&nonce=123` this link on the same tab
> > 6. See the cookies in Request headers for that specific page
> > 7. Paste the cookies in the plugin's settings
> > 
> > ![image](https://user-images.githubusercontent.com/3626859/179371572-14441caa-6124-4dd1-9d3f-ed77e43d5b9e.png)
> 
> Thank you, this fixed the issue for me. However, my cookies had a lot more parameters than yours, so I only copied the sub, csid, and ssid.

Glad to know that helped! By the way, my cookies too have a lot of parameters, but they are cropped in the screenshot I sent.
